trigger:
- master

pool:
  name: Default  # for self-hosted agent

steps:
- script: echo "Azure Pipeline for Gradle project without JAR"
  displayName: 'Start Message'

- script: gradle build
  displayName: 'Build the Project with Gradle'

- script: gradle run
  displayName: 'Run the Application'